CREATE TABLE Cliente (
  id BIGINT AUTO_INCREMENT NOT NULL,
   firstName VARCHAR(255) NOT NULL,
   lastName VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   zipCode VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   CONSTRAINT pk_cliente PRIMARY KEY (id)
);

ALTER TABLE Cliente ADD CONSTRAINT uc_cliente_cpf UNIQUE (cpf);

ALTER TABLE Cliente ADD CONSTRAINT uc_cliente_email UNIQUE (email);